"""Fill a run folder with everything a training job needs -- and an audit trail.

Called by ``sub_builder.sh`` on the login node, once per submission:

    python -m framework.client.prepare --config configs/train_X.yaml \
        --run-dir runs/<job_name>_<date>_<time>

After it returns, the run folder is self-contained:

    <run_dir>/
    ├── config.yaml               verbatim copy of the submitted config
    ├── untaught_blacklist.json   the exact exclusion (explicitly empty for control)
    ├── job.slurm                 fully materialized -- no environment variables
    ├── run_wrapper.sh            what the GPU node executes (chmod +x)
    └── checkpoints/              the trainer saves parameters here, by step

(log.out / log.err / client.log join them once the job runs.)

The GPU node never resolves anything: it executes ``run_wrapper.sh``, which
runs the trainer on ``<run_dir>/config.yaml``, and the trainer reads the
blacklist artifact sitting next to it. Elasticsearch is only ever touched here.
"""

from __future__ import annotations

import argparse
import getpass
import os
import shutil
import stat
from typing import Any, Dict, Optional, Sequence

from framework.node.artifact import ARTIFACT_NAME
from framework.node.config_env import UNTAUGHT_ROOT, load_config, resolve_path

from .es_blacklist import (
    build_artifact,
    empty_artifact,
    normalize_thresholds,
    write_artifact,
)

JOB_SLURM = "job.slurm"
RUN_WRAPPER = "run_wrapper.sh"
CONFIG_COPY = "config.yaml"
CHECKPOINTS_DIR = "checkpoints"


def generate_job_slurm(job: Dict[str, Any], run_dir: str, user: str) -> str:
    """The submission script, as fully parsed strings -- zero env variables.

    Reading it back months later must tell you exactly what was asked of SLURM,
    with no indirection through whatever the environment happened to hold.
    """
    return f"""#! /bin/sh
#SBATCH --job-name={job["name"]}
#SBATCH --output={run_dir}/log.out
#SBATCH --error={run_dir}/log.err
#SBATCH --partition={job["partition"]}
#SBATCH --time={job["max_time_minutes"]}
#SBATCH --signal=USR1@120
#SBATCH --nodes={job["nodes"]}
#SBATCH --ntasks={job["ntasks"]}
#SBATCH --mem={job["cpu_mem_mb"]}
#SBATCH --cpus-per-task={job["cpus_per_task"]}
#SBATCH --gpus={job["gpus"]}

# Created by: {user}

{run_dir}/{RUN_WRAPPER}
"""


def generate_run_wrapper(job: Dict[str, Any], run_dir: str) -> str:
    """What the GPU node executes. Absolute paths only, informative by design."""
    return f"""#!/bin/sh
# Generated by framework.client.prepare for job '{job["name"]}' -- do not edit.
# Everything this run used or produced lives in {run_dir}
set -eu

echo "=========================================================="
echo " job      : {job["name"]} (${{SLURM_JOB_ID:-no-slurm}})"
echo " node     : $(hostname)"
echo " started  : $(date)"
echo " run dir  : {run_dir}"
echo " config   : {run_dir}/{CONFIG_COPY}"
echo "=========================================================="

# Node-side environment: cd to Untaught/, variables, conda. No Elasticsearch --
# the blacklist was already resolved into this folder before submission.
. {UNTAUGHT_ROOT}/framework/node/set_node_env.sh

nvidia-smi || echo "warning: nvidia-smi unavailable"

torchrun --standalone --nproc-per-node={job["gpus"]} \\
  {UNTAUGHT_ROOT}/framework/node/train_untaught.py {run_dir}/{CONFIG_COPY}

echo "=========================================================="
echo " finished : $(date)"
echo "=========================================================="
"""


def prepare(config_path: str, run_dir: str) -> Dict[str, str]:
    """Populate ``run_dir``. Returns the paths written, keyed by role."""
    config_path = os.path.abspath(config_path)
    run_dir = os.path.abspath(run_dir)

    config = load_config(config_path)
    job = config["job"]
    untaught_cfg = config.get("untaught", {}) or {}
    # Fail on a threshold typo before anything is written or queried.
    normalize_thresholds(untaught_cfg)

    os.makedirs(os.path.join(run_dir, CHECKPOINTS_DIR), exist_ok=True)
    written: Dict[str, str] = {}

    # 1. The config, byte-for-byte -- comments included. The job trains from
    #    this copy, so later edits to configs/ cannot change what this run was.
    config_copy = os.path.join(run_dir, CONFIG_COPY)
    shutil.copyfile(config_path, config_copy)
    written["config"] = config_copy
    print(f"[prepare] config copy : {config_copy}")

    # 2. The exclusion, resolved. Control runs get an explicitly-empty artifact
    #    so the folder always answers "what was held out?" -- even with "nothing".
    blacklist = untaught_cfg.get("blacklist")
    if blacklist:
        blacklist = resolve_path(blacklist)
        if not os.path.isfile(blacklist):
            raise FileNotFoundError(f"[prepare] blacklist file not found: {blacklist}")
        artifact = build_artifact(blacklist, untaught_cfg)
        print(f"[prepare] blacklist   : {blacklist}")
        print(f"[prepare] index       : {artifact['index']} "
              f"(case_sensitive={artifact['case_sensitive']})")
        print(f"[prepare] thresholds  : {artifact['thresholds']}")
        for entity in artifact["entities"]:
            print(f"[prepare]   {entity['qid']:<12} {entity['num_chunks']:>9,} chunks  "
                  f"{entity['comment']}")
        print(f"[prepare] total       : {artifact['num_chunks']:,} unique chunks "
              f"({100.0 * artifact['num_chunks'] / 10_500_000:.4f}% of the corpus)")
    else:
        artifact = empty_artifact()
        print("[prepare] blacklist   : (none) -- CONTROL run, artifact written as "
              "explicitly empty")
    written["artifact"] = write_artifact(artifact, os.path.join(run_dir, ARTIFACT_NAME))
    print(f"[prepare] artifact    : {written['artifact']}")

    # 3. The submission script, materialized.
    slurm_path = os.path.join(run_dir, JOB_SLURM)
    with open(slurm_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_job_slurm(job, run_dir, getpass.getuser()))
    written["job_slurm"] = slurm_path
    print(f"[prepare] job.slurm   : {slurm_path}")

    # 4. The node-side wrapper, executable.
    wrapper_path = os.path.join(run_dir, RUN_WRAPPER)
    with open(wrapper_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(generate_run_wrapper(job, run_dir))
    os.chmod(wrapper_path, os.stat(wrapper_path).st_mode
             | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    written["run_wrapper"] = wrapper_path
    print(f"[prepare] run_wrapper : {wrapper_path}")

    return written


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="framework.client.prepare", description=__doc__)
    parser.add_argument("--config", required=True, help="a training run config (YAML)")
    parser.add_argument("--run-dir", required=True,
                        help="this submission's run folder (created if missing)")
    args = parser.parse_args(argv)

    prepare(args.config, args.run_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
